#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#execute phpstan
./vendor/bin/phpstan

if [ $? -ne 0 ]; then
    echo "Deu ruim com o phpstan";
    exit 1
fi;

#Tests
php artisan test
if [ $? -ne 0 ]; then
    echo "Deu ruim com algum teste";
    exit 1
fi;


#format staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$') || true

if [ -n "$STAGED_FILES" ]; then
    for FILE in $STAGED_FILES
    do
        ./vendor/bin/pint "$FILE" > /dev/null >&1
        git add "$FILE"
    done
fi

exit 0;