#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


#execute phpstan
# ./vendor/bin/phpstan analyse app --level 5

# if [ $? -ne 0 ]; then
#     echo "Deu ruim com o phpstan";
#     exit 1
# fi;


#format staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$') || true

for FILE in $STAGED_FILES
do
    .vendor/bin/pint "$FILE"
    git add "$FILE"

done;

exit 0
